# Site settings
title: Liverpool Code Club
description: >
  A fun way for kids to learn programming, through
  free, monthly classes led by trained professionals.
  Get creative building games, websites, and robots.
  Perfect for boys and girls aged 8 to 12 years.
baseurl: ""

# Build settings
markdown: kramdown
host: 0.0.0.0 # zarino.co.uk/post/jekyll-local-network
